CUDA_VISIBLE_DEVICES='0' python main.py \
    --seed 999 \
    --exp_dir checkpoints \
    --exp_name Exp1_Transformer_SE \
    --data_dir /mnt/2TB/user_chengyu/Corpus/noisy-vctk-16k \
    --num_workers 5 \
    --cuda \
    --log_interval 20 \
    --batch_size 8 \
    --learning_rate 1e-4 \
    --num_epochs 100 \
    --grad_accumulate_batches 1 \
    --log_grad_norm \
    --lr_decay 0 \
    --resume_dir True
